populateRelations function for populating the list of relations in the relations page
Mark-Jung/family-tree pull request #16
Opened 2019-04-18 01:24 UTC by puffinpoof

2019-04-18 02:50 UTC, Mark-Jung requested changes
Aside from a minor fix, lgtm

2019-04-18 02:50 UTC, Mark-Jung commented on screens/Relations/Relations.js
> +                params: {},
We need to add a param here, probably the item's id so that we can populate the details screen.

2019-05-06 05:37 UTC, Mark-Jung requested changes

2019-05-06 05:37 UTC, Mark-Jung commented on screens/Relations/Relations.js
> +                params: {},
Follow the article
https://medium.com/@shovonroy/how-to-properly-navigate-with-react-navigation-e38fe3bf7381
and it should be an easy fix.

2019-05-15 23:01 UTC, FOBkid20 commented
taken care of in other PRs

2019-05-15 23:01 UTC, closed without merging